### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by pzhlkj6612**
The word `interface` should be translated into "界面", it's the `Interface` in phrase `User Interface`.

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @pzhlkj6612  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by LisandroSu** [comment]
@pzhlkj6612 :

Thank you for your contribution.

Unfortunately your feedback cannot be accepted. Rejected/not implemented feedback is listed below:

Live sentence is acceptable.
		
Thank you for your time and support.
Microsoft C&E Localization Team

**Comment by pzhlkj6612** [comment]
@LisandroSu :
Sorry. But, elsewhere in this document, `interface` is translated as "界面", but here is the "接口", which I think is not accurate, although the reader may be able to understand the exact meaning of this "interface". Please consider it again.

**Comment by DHclly** [comment]
> @LisandroSu :
> Sorry. But, elsewhere in this document, `interface` is translated as "界面", but here is the "接口", which I think is not accurate, although the reader may be able to understand the exact meaning of this "interface". Please consider it again.

我个人觉得吧，叫用户界面和用户接口其实都挺合适的，这就像土豆可以叫土豆、马铃薯、洋芋，都没错。就看个人爱好了。

可以看看这个讨论：https://bbs.csdn.net/topics/390609236?page=1
我比较认同这个

> 对用户而言的，叫界面
>对程序而言的，叫接口

**Comment by pzhlkj6612** [comment]
> > @LisandroSu :
> > Sorry. But, elsewhere in this document, `interface` is translated as "界面", but here is the "接口", which I think is not accurate, although the reader may be able to understand the exact meaning of this "interface". Please consider it again.
> 
> 我个人觉得吧，叫用户界面和用户接口其实都挺合适的，这就像土豆可以叫土豆、马铃薯、洋芋，都没错。就看个人爱好了。
> 
> 可以看看这个讨论：https://bbs.csdn.net/topics/390609236?page=1
> 我比较认同这个
> 
> > 对用户而言的，叫界面
> > 对程序而言的，叫接口

嗯，我同意你的观点。

把那条回复发出后，我想了想，如果真有一个来读文档的人看到了这个词，那他也不太可能纠结“接口”到底是什么意思，毕竟都自己读文档了，对于许多翻译，在之前多多少少应该有过了解了。

<br>

谢谢。

**Pull request closed without merging**
