### PR TITLE
Update spa-services.md

### PR DESCRIPTION
**Pull request by yanshengjie**
Updated title and some other content.

### CODE REVIEW

**Comment by imba-tjd** [comment]
You should firstly replace 角度 with Angular and then replace 角 otherwise you would get Angular度.

Besides, I suggest not translating so many MT articles by yourself because the statement would probably not match with MS's style.

**Comment by LisandroSu** [comment]
Hello, @yanshengjie , 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by yanshengjie** [comment]
@imba-tjd Thanks for your advice.

**Comment by LisandroSu** [comment]
Hello, @yanshengjie ,

Thank you for your feedback and suggestion. 
 
The feedback has been partially accepted.. We will adjust  your feedback in order to comply with Microsoft Style Guide. We will release this article in the next localization release round accordingly.

Many thanks for your time and  support on this. 
 
Microsoft C&E Localization Team

**Pull request merged**
