### PR TITLE
Update concurrency.md

### PR DESCRIPTION
**Pull request by lynnedong**

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C3%5Cf9469637-972b-db6a-7ee4-a641c7d166d9%5CPullRequest%5C201710031828040421-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OlvXSPvvLmf4aR%2F4biwociYMyfPz50%2FTCt5EL75OqqA%3D&st=2017-10-03T18%3A24%3A01Z&se=2017-10-04T18%3A34%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @lynnedong, we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C20%5Cf9469637-972b-db6a-7ee4-a641c7d166d9%5CPullRequest%5C201710201348226044-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=D2FidkpVSN%2BHcTiLJJuxApTUE3SI0wO6AJymkM0UklM%3D&st=2017-10-20T13%3A43%3A25Z&se=2017-11-20T13%3A48%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
@lynnedong : Thank you for your feedback and suggestion! 

The feedback is considered. We will tune part of  your feedback in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
		
Microsoft C&E Localization Team

**Pull request merged**
