### PR TITLE
Replace "筛选器" to "过滤器"

### PR DESCRIPTION
**Pull request by stulzq**
Filter has long been translated as "过滤器" in various technical blogs and ASP. NET related technical books, so I suggest replacing "筛选器" to "过滤器". This will help developers to find this document more easily, because developers usually use the word "过滤器", based on the current "筛选器", developers can not locate this document through search.

### CODE REVIEW

**Comment by stulzq** [comment]
This is a comparison of search engine results.

image

**Comment by stulzq** [comment]
This is the translation of "Filter" in simplified Chinese books. (Listed technical books include ASP. NET and ASP. NET Core, because "Filter" on both platforms are the same)

BookName: ASP.NET Core跨平台开发从入门到实战
Author: 张剑桥
ISBN: 9787121311451
Chapter with"Filter": 7.10

BookName: ASP.NET MVC 5框架揭秘
Author: 蒋金楠
ISBN: 9787121237812
Chapter with"Filter": 12

and so on.

**Comment by ticianaciminari** [comment]
Hello, @stulzq 

Thanks for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by LisandroSu** [comment]
Hello, @stulzq 

Thank you for your feedback and suggestion. 
 
Unfortunately, we consider that 筛选器 & 筛选 are the preferred term though 过滤 can express similar meaning which is/are not fully aligned with our criteria for acceptance

Closing this PR since it does not apply

Thank you.

Kind regards,
 
Microsoft C&E Localization Team

**Pull request closed without merging**
