### PR TITLE
Master

### PR DESCRIPTION
**Pull request by FOWind**
I have translate the *Getting started with ASP.NET Core MVC and Entity Framework Core using Visual Studio (1 of 10)*,please review it

### CODE REVIEW

**Comment by gosali** [comment]
Hi @FOWind , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by FOWind** [comment]
I have modified the CRUD document which was translated by machine, corrected lots of grammatical mistake, making it easier to understand. Please review it.

**Comment by FOWind** [comment]
Today, I have modified the *Sorting, filtering, paging, and grouping - EF Core with ASP.NET Core MVC tutorial (3 of 10)* from MT and perfect the work done before.Please review it.

**Comment by gosali** [comment]
Hi @FOWind , we are still in discussing, will update the decision later soon.

For future PRs, we suggest you opening one PR with all the files changed at once? or One PR per File changed so as to track them differentially.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by jiangsheng** [comment]
示例应用程序是一个用于虚构的 Contoso 大学的网站
should be 
示例应用程序是个供一个虚构的 Contoso 大学使用的网站

**Comment by FOWind** [comment]
@gosali ，thanks for your suggestion. For the later modification I will create a new branch and open a new PR with the remaining 7 document of the ef-mvc.

**Comment by gosali** [comment]
Hi @FOWind,

Thank you for your cooperation.
Our suggestion is to submit a PR, and then if further changes are needed on different lines of the article, open a different PR, so as to keep track and process all the changes consistently.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @jiangsheng,

Please feel free to open a new PR with the suggested changes.

Thanks for your support,
Microsoft C&E Localization Team

**Pull request closed without merging**
