### PR TITLE
I started translating from Getting started with ASP.NET Core MVC and Entity Framework Core using Visual Studio

### PR DESCRIPTION
**Pull request by ltm0203**
I started translating from Getting started with ASP.NET Core MVC and Entity Framework Core using Visual Studio

### CODE REVIEW

**Comment by v-tisip** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/tutorials/razor-pages/model.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/tutorials/razor-pages/model.md) | :x:Error | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?branch=pr-zh-cn-9) | [Details](#user-content-aspnetcore%2Ftutorials%2Frazor-pages%2Fmodel.md)
[aspnetcore/fundamentals/logging.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/fundamentals/logging.md) | :x:Error | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/fundamentals/logging?branch=pr-zh-cn-9) | [Details](#user-content-aspnetcore%2Ffundamentals%2Flogging.md)
[aspnetcore/data/ef-mvc/crud.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/data/ef-mvc/crud.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/data/ef-mvc/crud?branch=pr-zh-cn-9) | [Details](#user-content-aspnetcore%2Fdata%2Fef-mvc%2Fcrud.md)
[aspnetcore/data/ef-mvc/intro.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/data/ef-mvc/intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/data/ef-mvc/intro?branch=pr-zh-cn-9) | [Details](#user-content-aspnetcore%2Fdata%2Fef-mvc%2Fintro.md)
[aspnetcore/includes/webApi/intro.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/includes/webApi/intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?branch=pr-zh-cn-9) | [Details](#user-content-aspnetcore%2Fincludes%2FwebApi%2Fintro.md)
[aspnetcore/tutorials/first-web-api.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/tutorials/first-web-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?branch=pr-zh-cn-9) | [Details](#user-content-aspnetcore%2Ftutorials%2Ffirst-web-api.md)
[aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/publishing/visual-studio-tools-for-docker.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/publishing/visual-studio-tools-for-docker?branch=pr-zh-cn-9) | [Details](#user-content-aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md)
[aspnetcore/getting-started.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/getting-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/getting-started?branch=pr-zh-cn-9) |
[aspnetcore/includes/install2.0.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/includes/install2.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/data/ef-mvc/intro?branch=pr-zh-cn-9) |
[aspnetcore/index.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/index?branch=pr-zh-cn-9) |
[aspnetcore/mvc/razor-pages/index.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/mvc/razor-pages/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/aspnet/core/mvc/razor-pages/index?branch=pr-zh-cn-9) |

<a name="aspnetcore%2Ftutorials%2Frazor-pages%2Fmodel.md"></a>
### [aspnetcore/tutorials/razor-pages/model.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/tutorials/razor-pages/model.md)
 - **Line 12**: **[Error]** Start line 19 exceeds total lines 15 when resolving &quot;[!code-csharp[Main](../../tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieContext.cs?range=1-12,14-17,19-21)]&quot;
 - **Line 58**: **[Warning]** Invalid file link:(~/tutorials/first-mvc-app/adding-model/_static/pmc.png).

<a name="aspnetcore%2Ffundamentals%2Flogging.md"></a>
### [aspnetcore/fundamentals/logging.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/fundamentals/logging.md)
 - **Line 41**: **[Error]** Unable to resolve [!code-csharp[](logging/sample/Controllers/TodoController.cs?name=snippet_LoggerDI&amp;highlight=7)]

. Can not find reference logging/sample/Controllers/TodoController.cs.
 - **Line 45**: **[Error]** Unable to resolve [!code-csharp[](logging/sample/Controllers/TodoController.cs?name=snippet_CallLogMethods&amp;highlight=3,7)]

. Can not find reference logging/sample/Controllers/TodoController.cs.
 - **Line 59**: **[Error]** Unable to resolve [!code-csharp[](logging/sample2/Program.cs?name=snippet_ExpandDefault&amp;highlight=16,17)]

. Can not find reference logging/sample2/Program.cs.
 - **Line 63**: **[Error]** Unable to resolve [!code-csharp[](logging/sample2/Program.cs?name=snippet_TemplateCode&amp;highlight=7)]

. Can not find reference logging/sample2/Program.cs.
 - **Line 71**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Startup.cs?name=snippet_AddConsoleAndDebug&amp;highlight=3,5-7)]

. Can not find reference logging/sample//Startup.cs.
 - **Line 131**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Controllers/TodoController.cs?name=snippet_CreateLogger&amp;highlight=7,10)]

. Can not find reference logging/sample//Controllers/TodoController.cs.
 - **Line 135**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Controllers/TodoController.cs?name=snippet_LoggerDI&amp;highlight=7)]

. Can not find reference logging/sample//Controllers/TodoController.cs.
 - **Line 145**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Controllers/TodoController.cs?name=snippet_CallLogMethods&amp;highlight=3,7)]

. Can not find reference logging/sample//Controllers/TodoController.cs.
 - **Line 212**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Controllers/TodoController.cs?name=snippet_CallLogMethods&amp;highlight=3,7)]

. Can not find reference logging/sample//Controllers/TodoController.cs.
 - **Line 214**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Core/LoggingEvents.cs?name=snippet_LoggingEvents)]

. Can not find reference logging/sample//Core/LoggingEvents.cs.
 - **Line 231**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Controllers/TodoController.cs?name=snippet_CallLogMethods&amp;highlight=3,7)]

. Can not find reference logging/sample//Controllers/TodoController.cs.
 - **Line 259**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Controllers/TodoController.cs?name=snippet_LogException&amp;highlight=3)]

. Can not find reference logging/sample//Controllers/TodoController.cs.
 - **Line 282**: **[Error]** Unable to resolve [!code-csharp[](logging/sample2/Program.cs?name=snippet_ExpandDefault&amp;highlight=15)]

. Can not find reference logging/sample2/Program.cs.
 - **Line 286**: **[Error]** Unable to resolve [!code-json[](logging/sample2/appsettings.json)]

. Can not find reference logging/sample2/appsettings.json.
 - **Line 294**: **[Error]** Unable to resolve [!code-csharp[](logging/sample2/Program.cs?name=snippet_FilterInCode&amp;highlight=4-5)]

. Can not find reference logging/sample2/Program.cs.
 - **Line 344**: **[Error]** Unable to resolve [!code-csharp[](logging/sample2/Program.cs?name=snippet_MinLevel&amp;highlight=3)]

. Can not find reference logging/sample2/Program.cs.
 - **Line 352**: **[Error]** Unable to resolve [!code-csharp[](logging/sample2/Program.cs?name=snippet_FilterFunction&amp;highlight=5-13)]

. Can not find reference logging/sample2/Program.cs.
 - **Line 360**: **[Error]** Unable to resolve [!code-csharp[](logging/sample/Startup.cs?name=snippet_AddConsoleAndDebugWithFilter&amp;highlight=6-7)]

. Can not find reference logging/sample/Startup.cs.
 - **Line 366**: **[Error]** Unable to resolve [!code-csharp[](logging/sample/Startup.cs?name=snippet_FactoryFilter&amp;highlight=6-11)]

. Can not find reference logging/sample/Startup.cs.
 - **Line 380**: **[Error]** Unable to resolve [!code-csharp[](logging/sample//Controllers/TodoController.cs?name=snippet_Scopes&amp;highlight=4-5,13)]

. Can not find reference logging/sample//Controllers/TodoController.cs.
 - **Line 388**: **[Error]** Unable to resolve [!code-csharp[](logging/sample2/Program.cs?name=snippet_Scopes&amp;highlight=4)]

. Can not find reference logging/sample2/Program.cs.
 - **Line 394**: **[Error]** Unable to resolve [!code-csharp[](logging/sample/Startup.cs?name=snippet_Scopes&amp;highlight=6)]

. Can not find reference logging/sample/Startup.cs.
 - **Line 449**: **[Error]** Unable to resolve [!code-json[](logging/sample//appsettings.json)]

. Can not find reference logging/sample//appsettings.json.
 - **Line 580**: **[Error]** Unable to resolve [!code-csharp[](logging/sample/Startup.cs?name=snippet_TraceSource&amp;highlight=9-12)]

. Can not find reference logging/sample/Startup.cs.
 - **Line 501**: **[Warning]** Invalid file link:(~/fundamentals/logging/_static/perfview-additional-providers.png).
 - **Line 606**: **[Warning]** Invalid file link:(~/fundamentals/logging/_static/azure-logging-settings.png).

<a name="aspnetcore%2Fdata%2Fef-mvc%2Fcrud.md"></a>
### [aspnetcore/data/ef-mvc/crud.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/data/ef-mvc/crud.md)
 - **Line 38**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/student-details.png).
 - **Line 40**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/student-create.png).
 - **Line 42**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/student-edit.png).
 - **Line 44**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/student-delete.png).
 - **Line 142**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/student-details.png).
 - **Line 181**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/fiddler.png).
 - **Line 201**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/date-error.png).
 - **Line 265**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/student-edit.png).
 - **Line 307**: **[Warning]** Invalid file link:(~/data/ef-mvc/crud/_static/student-delete.png).

<a name="aspnetcore%2Fdata%2Fef-mvc%2Fintro.md"></a>
### [aspnetcore/data/ef-mvc/intro.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/data/ef-mvc/intro.md)
 - **Line 64**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/students-index.png).
 - **Line 66**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/student-edit.png).
 - **Line 84**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/new-project.png).
 - **Line 95**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/new-aspnet.png).
 - **Line 121**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/home-page.png).
 - **Line 138**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/data-model-diagram.png).
 - **Line 147**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/student-entity.png).
 - **Line 162**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/enrollment-entity.png).
 - **Line 181**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/course-entity.png).
 - **Line 291**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/add-depend.png).
 - **Line 315**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/scaffold-student.png).
 - **Line 351**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/home-page-narrow.png).
 - **Line 353**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/students-index.png).
 - **Line 371**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/ssox-tables.png).
 - **Line 375**: **[Warning]** Invalid file link:(~/data/ef-mvc/intro/_static/ssox-student-table.png).

<a name="aspnetcore%2Fincludes%2FwebApi%2Fintro.md"></a>
### [aspnetcore/includes/webApi/intro.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/includes/webApi/intro.md)
 - **Line 17**: **[Warning]** Invalid file link:(~/tutorials/first-web-api/_static/architecture.png).
 - **Line 17**: **[Warning]** Invalid file link:(~/tutorials/first-web-api/_static/architecture.png).
 - **Line 17**: **[Warning]** Invalid file link:(~/tutorials/first-web-api/_static/architecture.png).

<a name="aspnetcore%2Ftutorials%2Ffirst-web-api.md"></a>
### [aspnetcore/tutorials/first-web-api.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/tutorials/first-web-api.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/tutorials/first-web-api/_static/new-project.png).
 - **Line 51**: **[Warning]** Invalid file link:(~/tutorials/first-web-api/_static/web-api-project.png).
 - **Line 100**: **[Warning]** Invalid file link:(~/tutorials/first-web-api/_static/new_controller.png).

<a name="aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md"></a>
### [aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/ltm0203/Docs.zh-cn/blob/master/aspnetcore/publishing/visual-studio-tools-for-docker.md)
 - **Line 39**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/settings-shared-drives-win.png).
 - **Line 47**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/project-add-docker-support.png).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/right-click-add-docker-support.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Cf9469637-972b-db6a-7ee4-a641c7d166d9%5CPullRequest%5C201711070536513418-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bsgfjy1LngZfOkRwOlQF2kdXT%2BhAjxFRInsLIv5Fq1M%3D&st=2017-11-07T05%3A36%3A17Z&se=2017-12-08T05%3A41%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @ltm0203 , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @ltm0203 , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by ltm0203** [comment]
Ok, I'll close it.

**Pull request closed without merging**
