### PR TITLE
I have translated ef-mvc tutorial

### PR DESCRIPTION
**Pull request by FOWind**
I have translated ten passages of the ef-mvc tutorial, making it easier to understand for Chinese. Please review it.

### CODE REVIEW

**Comment by gosali** [comment]
Hi @FOWind , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by FOWind** [comment]
@v-radelg what does ‘lm feed’ mean ?

**Comment by v-radelg** [comment]
Hi @FOWind ,the suggestions are reviewed by a language moderator and sometimes they make some linguistic or style changes that we need to apply in the PR. That's the reason you see the commit "LM Feedback"

Thanks for your support,
Microsoft C&E Localization Team

**Comment by FOWind** [comment]
@v-radelg I wonder whether if I need to make a corresponding revision .

**Comment by v-radelg** [comment]
@FOWind thank you for your proactivity, but it is not necessary. Once the language moderator finish we will merge your PR accordingly.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-maudel** [comment]
Hello, @FOWind ,

Thank you for your feedback and suggestion. 
 
The feedback has been partially accepted.. We will adjust  your feedback in order to comply with Microsoft Style Guide. We will release this article in the next localization release round accordingly.

Many thanks for your time and  support on this. 
 
Microsoft C&E Localization Team

**Pull request merged**
