### PR TITLE
Amendments for in-memory cache.

### PR DESCRIPTION
**Pull request by yanxiaodi**
Amendments for in-memory cache.

I'm a little confused because the source code of this article is different with the current published version. I mean the last section: Additional resources. There are 6 items on the published page but there are only 2 items in the source code.

Please let me know if anyone knows how to amend this section.

### CODE REVIEW

**Comment by v-maudel** [comment]
Hello, @yanxiaodi , 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by v-maudel** [comment]
Hi @yanxiaodi , 
We noted that you added a new file to this PR. 
We are sending it to review as well,  Although we would like to ask you, in future suggestions, to create a new Pull Request for each new file you modify.

Kind regards,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@yanxiaodi , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Comment by yanxiaodi** [comment]
@v-maudel Sorry, I'll create a new PR for the next time.

**Pull request merged**
